### ISSUE TITLE
ADD samples/hello-world@0.0.1

### ISSUE THREAD

**Issue by jkutner** [jkutner/buildpack-registry#1]
### Data

```toml
id = "samples/hello-world"
version = "0.0.1"
addr = "index.docker.io/jkutner/hello-buildpack@sha256:680decf7c081142cead933cb83ffe97a75f4926259eeb78e61f4709d7ae71480"
```
